export const LOAD_CONNECTER = 'LOAD_CONNECTER';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const CONNECT_ERRORS = 'CONNECT_ERRORS'
export const LOADING_TRUE = 'LOADING_TRUE'
export const LOADING_FALSE = 'LOADING_FALSE'